# This File uses Shell-Patterns
port: 3060
interval: 15

directories:
  - name: logs
    path: /var/log
    recursive: true
    include_patterns:
      - "*.log"
      - "*.err"
    include_dirs:
      - nginx
      - apache2

  - name: tmp
    path: /tmp
    recursive: false